Repository openrewrite/rewrite-kotlin, pull requests merged in 2023-08, with the labels that each got.

#209 Fix variable declaration printer error
  src/main/java/org/openrewrite/kotlin/internal/KotlinPrinter.java
  src/test/java/org/openrewrite/kotlin/tree/ForLoopTest.java
  src/test/java/org/openrewrite/kotlin/tree/VariableDeclarationTest.java
Labels: bug

#213 New `AddImport` visitor
  src/main/java/org/openrewrite/kotlin/AddImport.java
  src/main/java/org/openrewrite/kotlin/internal/KotlinParserVisitor.java
  src/main/java/org/openrewrite/kotlin/internal/KotlinPrinter.java
  src/main/java/org/openrewrite/kotlin/service/KotlinImportService.java
  src/main/java/org/openrewrite/kotlin/service/package-info.java
  src/main/java/org/openrewrite/kotlin/style/ImportLayoutStyle.java
  src/main/java/org/openrewrite/kotlin/tree/K.java
  src/test/java/org/openrewrite/kotlin/AddImportTest.java
  src/test/java/org/openrewrite/kotlin/tree/ImportTest.java
Labels: bug, enhancement

#221 Add RemoveTrailingSemicolon recipe
  src/main/java/org/openrewrite/kotlin/cleanup/EqualsMethodUsage.java
  src/main/java/org/openrewrite/kotlin/cleanup/ImplicitParameterInLambda.java
  src/main/java/org/openrewrite/kotlin/cleanup/RemoveTrailingSemicolon.java
  src/main/java/org/openrewrite/kotlin/cleanup/ReplaceCharToIntWithCode.java
  src/main/java/org/openrewrite/kotlin/cleanup/package-info.java
  src/main/java/org/openrewrite/kotlin/internal/KotlinPrinter.java
  src/test/java/org/openrewrite/kotlin/cleanup/RemoveTrailingSemicolonTest.java
Labels: recipe

#226 Correct parsing of constructor args prefix
  src/main/java/org/openrewrite/kotlin/internal/KotlinParserVisitor.java
  src/test/java/org/openrewrite/kotlin/tree/MethodDeclarationTest.java
Labels: bug

#223 Fix printing of `return` with label
  src/main/java/org/openrewrite/kotlin/internal/KotlinPrinter.java
  src/test/java/org/openrewrite/kotlin/tree/ReturnTest.java
Labels: bug

#234 Fix trailing commas in `when` conditions and lambda parameters
  src/main/java/org/openrewrite/kotlin/internal/KotlinParserVisitor.java
  src/main/java/org/openrewrite/kotlin/internal/KotlinPrinter.java
  src/test/java/org/openrewrite/kotlin/tree/LambdaTest.java
  src/test/java/org/openrewrite/kotlin/tree/WhenTest.java
Labels: bug

#217 Kotlin 1.9.0
  build.gradle.kts
  src/main/java/org/openrewrite/kotlin/KotlinParser.java
  src/main/java/org/openrewrite/kotlin/KotlinTypeMapping.java
  src/main/java/org/openrewrite/kotlin/KotlinTypeSignatureBuilder.java
  src/main/java/org/openrewrite/kotlin/internal/KotlinParserVisitor.java
  src/main/java/org/openrewrite/kotlin/internal/KotlinSource.java
  src/main/java/org/openrewrite/kotlin/internal/PsiTree.java
  src/main/java/org/openrewrite/kotlin/marker/AnnotationCallSite.java
  src/main/java/org/openrewrite/kotlin/marker/By.java
  src/main/java/org/openrewrite/kotlin/marker/CheckNotNull.java
  src/main/java/org/openrewrite/kotlin/marker/Extension.java
  src/main/java/org/openrewrite/kotlin/marker/GenericType.java
  src/main/java/org/openrewrite/kotlin/marker/Implicit.java
  src/main/java/org/openrewrite/kotlin/marker/IsNullSafe.java
  src/main/java/org/openrewrite/kotlin/marker/IsNullable.java
  src/main/java/org/openrewrite/kotlin/marker/KObject.java
  src/main/java/org/openrewrite/kotlin/marker/LogicalComma.java
  src/main/java/org/openrewrite/kotlin/marker/Modifier.java
  src/main/java/org/openrewrite/kotlin/marker/NotIs.java
  src/main/java/org/openrewrite/kotlin/marker/OmitBraces.java
  src/main/java/org/openrewrite/kotlin/marker/OmitEquals.java
  src/main/java/org/openrewrite/kotlin/marker/PrimaryConstructor.java
  src/main/java/org/openrewrite/kotlin/marker/Semicolon.java
  src/main/java/org/openrewrite/kotlin/marker/SingleExpressionBlock.java
  src/main/java/org/openrewrite/kotlin/marker/SpreadArgument.java
  src/main/java/org/openrewrite/kotlin/marker/TrailingLambdaArgument.java
  src/main/java/org/openrewrite/kotlin/marker/TypeReferencePrefix.java
  src/main/java/org/openrewrite/kotlin/tree/K.java
  src/main/kotlin/org/openrewrite/kotlin/KotlinTypeMapping.kt
  src/main/kotlin/org/openrewrite/kotlin/KotlinTypeSignatureBuilder.kt
  src/main/kotlin/org/openrewrite/kotlin/internal/KotlinParserVisitor.kt
  src/main/kotlin/org/openrewrite/kotlin/internal/KotlinSource.kt
  src/test/java/org/openrewrite/kotlin/KotlinTypeGoatTest.java
  src/test/java/org/openrewrite/kotlin/KotlinTypeMappingTest.java
  src/test/java/org/openrewrite/kotlin/KotlinTypeSignatureBuilderTest.java
  src/test/java/org/openrewrite/kotlin/tree/.editorconfig
  src/test/java/org/openrewrite/kotlin/tree/AnnotationTest.java
  src/test/java/org/openrewrite/kotlin/tree/EnumTest.java
  src/test/java/org/openrewrite/kotlin/tree/LiteralTest.java
  src/test/java/org/openrewrite/kotlin/tree/MethodDeclarationTest.java
Labels: enhancement

#241 Support anonymous objects without supertype
  src/main/java/org/openrewrite/kotlin/internal/KotlinPrinter.java
  src/main/kotlin/org/openrewrite/kotlin/internal/KotlinParserVisitor.kt
  src/test/java/org/openrewrite/kotlin/tree/VariableDeclarationTest.java
Labels: bug

#239 Support whitespace in package and imports
  src/main/kotlin/org/openrewrite/kotlin/internal/KotlinParserVisitor.kt
  src/test/java/org/openrewrite/kotlin/tree/ClassDeclarationTest.java
Labels: bug

#225 Correct printing of `!in` expressions
  src/main/java/org/openrewrite/kotlin/format/MinimumViableSpacingVisitor.java
  src/main/java/org/openrewrite/kotlin/format/SpacesVisitor.java
  src/main/java/org/openrewrite/kotlin/internal/KotlinPrinter.java
  src/main/java/org/openrewrite/kotlin/tree/K.java
  src/main/kotlin/org/openrewrite/kotlin/internal/KotlinParserVisitor.kt
  src/test/java/org/openrewrite/kotlin/tree/BinaryTest.java
Labels: bug

#245 Parser must not gobble up characters beyond end of string element
  src/main/kotlin/org/openrewrite/kotlin/internal/KotlinParserVisitor.kt
  src/test/java/org/openrewrite/kotlin/tree/StringTest.java
Labels: bug

#238 Support calling super constructor with anonymous lambda argument
  src/main/kotlin/org/openrewrite/kotlin/internal/KotlinParserVisitor.kt
  src/test/java/org/openrewrite/kotlin/tree/MethodInvocationTest.java
Labels: bug

#243 Correctly handle empty parens before trailing lambda
  src/main/kotlin/org/openrewrite/kotlin/internal/KotlinParserVisitor.kt
  src/test/java/org/openrewrite/kotlin/tree/MethodInvocationTest.java
Labels: bug

#248 Fix printing of trailing comma in primary constructor of class
  src/main/java/org/openrewrite/kotlin/internal/KotlinPrinter.java
  src/test/java/org/openrewrite/kotlin/tree/ClassDeclarationTest.java
Labels: bug

#249 Correctly parse lambdas with multiple destruct params
  src/main/kotlin/org/openrewrite/kotlin/internal/KotlinParserVisitor.kt
  src/test/java/org/openrewrite/kotlin/tree/LambdaTest.java
Labels: bug

#250 Better support for auto-formatting extension methods
  src/main/java/org/openrewrite/kotlin/format/MinimumViableSpacingVisitor.java
  src/main/java/org/openrewrite/kotlin/format/SpacesVisitor.java
  src/test/java/org/openrewrite/kotlin/format/AutoFormatVisitorTest.java
Labels: enhancement

#252 Support references to imported members
  src/main/kotlin/org/openrewrite/kotlin/internal/KotlinParserVisitor.kt
  src/test/java/org/openrewrite/kotlin/tree/MethodInvocationTest.java
Labels: bug

#257 Align `KotlinParser.Builder` API with `JavaParser.Builder`
  src/main/java/org/openrewrite/kotlin/KotlinParser.java
Labels: enhancement
